### ISSUE TITLE
README.md > Our Lectures > Empty Links

### ISSUE THREAD

**Issue by jcllobet** [telecombcn-dl/lectures-all#1]
* [Natural Language Processing with DNN](nlp.md) --> **nlp.md** is empty
* [Speech Processing with DNN](speech.md) --> **speech.md** is empty
* [Multimodal Learning with DNN](cross-modal.md) --> should point to **multimodal.md**
* [Hands on DNN](hands-on) --> should point to **hands-on.md**

Have only seen two lectures so far but thank you for the awesome quality & content.

**Comment by xavigiro** [comment]
I think everything is fixed now. Thanks for pointing at it !
